*  [[http://morizyun.github.io/blog/ruby-design-pattern-14-abstract-factory/][アブストラクトファクトリ Ruby 2.0.0 デザインパターン速攻習得]]

アブストラクトファクトリは、矛盾のないオブジェクトの生成を行うためのパ
ターンです。

** アブストラクトファクトリのメリットは？

   - 関連し合うオブジェクトの集まりを生成することができる
   - 整合性が必要となるオブジェクト群を誤りなしに生成できる

** 参考サイト
   - [[http://www.techscore.com/tech/DesignPattern/AbstractFactory.html/][AbstractFactory パターン | TECHSCORE(テックスコア)]]

   - [[https://ja.wikipedia.org/wiki/Abstract_Factory_%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3][Abstract Factory パターン - Wikipedia]]

   - [[http://www.itsenka.com/contents/development/designpattern/abstract_factory.html][Abstract Factory パターン - デザインパターン入門 - IT専科]]


** 動物と植物からなる生態系の生成

   - 動物を表すクラス:
     - アヒルを表すDuckクラスは、食事(eat)メソッドを持っている
     - カエルを表すFrogクラスは、食事(eat)メソッドを持っている

   - 植物を表すクラス:
     - 藻を表すAlgaeクラスは、成長(grow)メソッドを持っている
     - スイレンを表すWaterLilyクラスは、成長(grow)メソッドを持っている

   - 池の生態系を生成するクラス:
     * コンストラクタで動物と植物を定義する
     * 動物、植物のオブジェクトを返すメソッドを持っている

   - 池の環境(動物と植物の組み合わせ)は次の2種類のみが許されている
     * DuckとWaterLily
     * FrogとAlgae

   この池の環境の制約を守ること、言い換えると矛盾のないオブジェクトの
   組み合わせを作るのが「Abstract Factoryパターン」です。

** Abstract Factoryの構成 

   Abstract Factoryは次の要素で構成されています。

   - AbstractFactory :: ConcreteFactoryの共通部分の処理を行う
     
     この例ではOrganismFactory

   - AbstractProduct1,2 :: AbstractFactoryによって生成される側の
        Product毎の共通インタフェース

     この例では，Animal と Plant

   - ConcreteFactory :: 制約を守り，実際の生態系の生成を行う, 
     
     この例では, FrogAndAlgaeFactory と DuckAndWaterLilyFactory

   - ConcreteProduct1 :: この例では、Animal の具体化の，Duck と Frog

   - ConcreteProduct2 :: この例では、Plant の具体化の，Algae と WaterLilly


** directory

#+BEGIN_SRC sh :results output :exports both
sh ~/COMM/bin/lstree abstract_factory
#+END_SRC

#+RESULTS:
#+begin_example
abstract_factory@Sun Feb  5 15:18:34 JST 2017
+-animal.rb
+-animals-+-duck.rb
|         +-frog.rb
+-organism_factories-+-duck_and_waterlily.rb
|                    +-frog_and_algae.rb
+-organism_factory.rb
+-plant.rb
+-plants-+-algae.rb
|        +-waterlily.rb
+-test_duck_and_waterlily_factory.rb
+-test_frog_and_algae_factory.rb
#+end_example


** 抽象的な OrganismFactory, Animal, Plant

#+BEGIN_SRC ruby :tangle abstract_factory/organism_factory.rb :mkdirp y
class OrganismFactory
  def initialize(number_animals, number_plants)
    @animals = []
    number_animals.times do |i|
      animal = new_animal("動物#{i}")
      @animals << animal 
    end

    @plants = []
    number_plants.times do |i|
      plant = new_plant("植物#{i}")
      @plants << plant 
    end
  end

  def get_plants
    @plants
  end

  def get_animals
    @animals
  end
  
end
 #+END_SRC

 #+BEGIN_SRC ruby :tangle abstract_factory/animal.rb :mkdirp yes
class Animal

  def eat
    puts "Animalは食べるものですから。"
  end
  
end
 #+END_SRC

 #+BEGIN_SRC ruby :tangle abstract_factory/plant.rb :mkdirp yes
class Plant

  def grow
    puts "Plant は成長するものですから。"
  end
  
end
 #+END_SRC

    
** 具体的な OrganismFactory

#+BEGIN_SRC ruby :tangle abstract_factory/organism_factories/frog_and_algae.rb :mkdirp yes
require 'abstract_factory/organism_factory'
require 'abstract_factory/animals/frog.rb'
require 'abstract_factory/plants/algae.rb'

class FrogAndAlgaeFactory < OrganismFactory
  private

  def new_animal(name)
    Frog.new(name)
  end

  def new_plant(name)
    Algae.new(name)
  end
end
#+END_SRC

#+BEGIN_SRC ruby :tangle abstract_factory/organism_factories/duck_and_waterlily.rb :mkdirp yes
require 'abstract_factory/organism_factory'
require 'abstract_factory/animals/duck.rb'
require 'abstract_factory/plants/waterlily.rb'

class DuckAndWaterLilyFactory < OrganismFactory
  private

  def new_animal(name)
    Duck.new(name)
  end

  def new_plant(name)
    WaterLily.new(name)
  end
end

#+END_SRC

** 具体的な動物 animals/

#+BEGIN_SRC ruby :tangle abstract_factory/animals/duck.rb :mkdirp yes
require 'abstract_factory/animal'

class Duck < Animal
  def initialize(name)
    @name = name
  end

  def eat
    puts "duck #{@name} は食事中です."
    super
  end
end
#+END_SRC    

#+BEGIN_SRC ruby :tangle abstract_factory/animals/frog.rb :mkdirp yes
require 'abstract_factory/animal'

class Frog < Animal
  def initialize(name)
    @name = name
  end

  def eat
    puts "frog #{@name} は食事中です."
    super
  end
end
#+END_SRC    

** 具体的な植物達 plants/

#+BEGIN_SRC ruby :tangle abstract_factory/plants/algae.rb :mkdirp yes
require 'abstract_factory/plant'
class Algae < Plant
  def initialize(name)
    @name = name
  end

  def grow
    puts("藻 #{@name} は成長中です.")
    super
  end
  
end
#+END_SRC

#+BEGIN_SRC ruby :tangle abstract_factory/plants/waterlily.rb :mkdirp yes
require 'abstract_factory/plant'

class WaterLily < Plant
  def initialize(name)
    @name = name
  end

  def grow
    puts("睡蓮 #{@name} は成長中です.")
  end
  
end
#+END_SRC

** test

#+BEGIN_SRC ruby :tangle abstract_factory/test_frog_and_algae_factory.rb :results output
$: << "."

require 'abstract_factory/organism_factory'
require 'abstract_factory/organism_factories/frog_and_algae'

factory = FrogAndAlgaeFactory.new(4,1)
animals = factory.get_animals
animals.each do |animal| 
  animal.eat
end

plants = factory.get_plants
plants.each do |plant|
  plant.grow
end


#+END_SRC

#+RESULTS:
#+begin_example
frog 動物0 は食事中です.
Animalは食べるものですから。
frog 動物1 は食事中です.
Animalは食べるものですから。
frog 動物2 は食事中です.
Animalは食べるものですから。
frog 動物3 は食事中です.
Animalは食べるものですから。
藻 植物0 は成長中です.
Plant は成長するものですから。
#+end_example



#+BEGIN_SRC ruby :tangle abstract_factory/test_duck_and_waterlily_factory.rb :results output
$: << "."

require 'abstract_factory/organism_factory'
require 'abstract_factory/organism_factories/duck_and_waterlily'

factory = DuckAndWaterLilyFactory.new(4,1)
animals = factory.get_animals
animals.each do |animal| 
  animal.eat
end

plants = factory.get_plants
plants.each do |plant|
  plant.grow
end


#+END_SRC

#+RESULTS:
: duck 動物0 は食事中です.
: Animalは食べるものですから。
: duck 動物1 は食事中です.
: Animalは食べるものですから。
: duck 動物2 は食事中です.
: Animalは食べるものですから。
: duck 動物3 は食事中です.
: Animalは食べるものですから。
: 睡蓮 植物0 は成長中です.

