* makefile

** header 

#+BEGIN_SRC makefile :tangle Makefile
MYHOME = ../
ORG = $(MYHOME)/org/
SITE = $(MYHOME)/docs/
DIR = ./
SHELL = zsh
DATE = `date`
#+END_SRC

** pages

#+BEGIN_SRC makefile :tangle Makefile
HTMLS = index.html \
lects.html \
ruby.html \
emacs.html \
oo.html
#+END_SRC

#+BEGIN_SRC makefile :tangle Makefile

all: $(HTMLS)


push:
	git push -u origin master

index.html: info/common-header.org 
lects.html: $(wildcard lects/*.org) info/common-header.org 
ruby.html: $(wildcard ruby/*.org) info/common-header.org 
emacs.html: $(wildcard emacs/*.org) info/common-header.org 
oo.html: $(wildcard oo/*.org) info/common-header.org 
meta-ruby.html: $(wildcard meta-ruby/*.org) info/common-header.org 
note.html: $(wildcard note/*.org) info/common-header.org 

#+END_SRC

** generating html rules

#+BEGIN_SRC makefile :tangle Makefile

.SUFFIXES: .org .html
.org.html: info/common-header.org 
	$(HOME)/bin/org2html $<
	sed -e 's/http:\/\//https:\/\//g' $@ | sed -e 's/https:\/\/www.pirilampo.org/https:\/\/wiki.cis.iwate-u.ac.jp\/~suzuki\/org-html-theme/' > $(SITE)/$@
#	cp -p $@  $(SITE)/$@
	git add  $(SITE)/$@ 
	git commit -a -m "daily $(DATE)"

.PHONY: clean
clean:
	rm -f *.html
	rm -f *~ */*~

#+END_SRC

#+BEGIN_SRC sh
make all

#+END_SRC

